# Tests for general `setup-bd` configurations.

name: BD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 00:00.

jobs:

  # Default test configurations.
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: example
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.12.4, stable, beta, dev]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print BD_HOME
        run: echo "BD SDK installed in $BD_HOME"
      - run: bd pub get
      - run: bd run bin/main.bd
      - run: bd analyze
      - run: bd test

  # Test the raw SDK flavor.
  test_raw:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [dev, main]
        flavor: [raw]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.bd
          bd hello.bd

  # Test the architecture input parameter.
  test_arch:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          architecture: ia32

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.bd
          bd hello.bd

  # Test inferring the channel from the sdk parameter.
  test_inferred_channels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [2.12.0-29.10.beta]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}
          architecture: ia32

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.bd
          bd hello.bd
      - run: bd --version
